apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fraudapi
  namespace: order-uat
  annotations:
    kubernetes.io/ingress.class: nginx-private
  labels:
    app: fraudapi
    tier: uat
spec:
  rules:
  - host: fraudservice.uat.lifeway.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fraudapi
          servicePort: 9000
