version: '3'
services:
   data_container:
      image: debian:jessie
      entrypoint: /bin/echo fraudService data volume
   mongo:
      image: 'mongo:3.4.1'
      ports:
         - '27017:27017'
      volumes:
         - 'mongo:/data/db'
   zookeeper:
      image: wurstmeister/zookeeper:latest
      ports:
         - 2181:2181
   kafka:
      image: wurstmeister/kafka:0.10.1.1
      environment:
         KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
         KAFKA_ADVERTISED_PORT: 9092
         KAFKA_CREATE_TOPICS: publicOrderProcessing:1:1,CommerceShared:1:1
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      ports:
         - 9092:9092
      links:
         - zookeeper
volumes:
   mongo: