apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fraudapi
  namespace: order-int
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: fraudapi
  targetCPUUtilizationPercentage: 100
